---
title: "A1-3-TabulateData"
output: html_document
---

```r
library(shiny)
library(tidyverse)
library(rio)
library(ggthemes)

adult <- read.csv("adult.csv")
head(adult)

# UI layout
ui = shinyUI(fluidPage(
    br(),
    #1: Project title 
    titlePanel("Correlation between different demographics on Income"),
    p("Variables that have an effect on whether an individual makes <50k or more >50k."),
    
    #2: Adding first fluidrow to input country:
    fluidRow(
        column(12, 
               wellPanel(selectInput("country", "1.Select Country", choices = c("United-States", "India", "Columbia", "England")))
        )
    ),
    
    #3: Adding second fluidrow for continuous variables:
    fluidRow(
        column(3, 
               wellPanel(
                   p("Select a continuous variable and graph type to view"),
                   radioButtons("continuous_variable", "2.Continuous", choices = c("hours_per_week", "age")),   
                   radioButtons("graph_type", "3.Graph", choices = c("boxplot", "histogram"))
               )
        ),
        column(9, plotOutput("p1")) 
    ),
    
    #4: Adding third fluidrow to control how to plot the categorical variables
    fluidRow(
        column(3, 
               wellPanel(
                   p("Select a categorical variable to view bar chart on the right. Use the check box to view a stacked bar chart to combine the income levels into one graph."),
                   radioButtons("categorical_variable", "4.Category", choices = c("sex", "race", "education", "workclass")),
                   checkboxInput("is_stacked", "Stacked Barchart", value = FALSE)
               )
        ),
        column(9, plotOutput("p2"))
    )
))

# Server logic
server = shinyServer(function(input, output) {
    adult = import("adult.csv")               
    names(adult) = tolower(names(adult))      
    
    df_country <- reactive({
        adult %>% filter(native_country == input$country)
    })
    
    #5: Creating histogram and boxplot 
    output$p1 <- renderPlot({
        if (input$graph_type == "histogram") {
            ggplot(df_country(), aes_string(x = input$continuous_variable)) +
                geom_histogram(color = "red", fill = "coral") +  
                labs(y = "Number of People", title = paste("Trend of", input$continuous_variable)) +  
                facet_wrap(~prediction) + 
                theme_light()
        } else {
            ggplot(df_country(), aes_string(y = input$continuous_variable)) +
                geom_boxplot(color = "blue", fill = "cyan") +  
                coord_flip() +  
                labs(x = "Number of People", title = paste("Boxplot of", input$continuous_variable)) + 
                facet_wrap(~prediction) +    
                theme_light()
        }
    })
    
    #6: Create bar chart and stacked chart for categorical variables
    output$p2 <- renderPlot({
        p <- ggplot(df_country(), aes_string(x = input$categorical_variable)) +
            labs(y = "Number of People", title = (paste("Trend of", input$categorical_variable))) +  
            theme_light() +
            theme(axis.text.x = element_text(angle = 35), legend.position = "bottom")    
        
        if (input$is_stacked) {
            p + geom_bar(aes(fill = prediction))
        } else {
            p + geom_bar(aes_string(fill = input$categorical_variable)) + 
                facet_wrap(~prediction)
        }
    })
})

shinyApp(ui = ui, server = server)
